version: '3'

services:
  cron:
    build:
      context: ../cron
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: melvil_cron
  web:
    build:
      context: ..
      dockerfile: './docker/Dockerfile'
    command: sh './docker/run.sh'
    volumes:
      - ..:/code
    env_file:
      - .env
    environment:
        - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - "postgresql"
    container_name: melvil_web_dev

  postgresql:
      image: postgres
      restart: always
      volumes:
       - ./data/postgresql:/var/lib/postgresql
      env_file:
      - .env
      ports:
        - "5432:5432"
      container_name: melvil_postgres_dev
