version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: './docker/Dockerfile'
    command: sh './docker/run.sh'
    volumes:
      - ..:/code
    env_file:
      - .env
    environment:
        - DB_USER=psql_user
        - DB_PASSWORD=Ab132xw
        - DB_NAME=psql_db
        - DB_HOST=postgresql
        - DB_PORT=5432
        - DB_ENGINE=postgresql
        - ENV=dev
    ports:
      - "5000:5000"
    depends_on:
      - "postgresql"

  postgresql:
      image: postgres
      restart: always
      volumes:
       - ./data/postgresql:/var/lib/postgresql
      environment:
        - POSTGRES_USER=psql_user
        - POSTGRES_PASSWORD=Ab132xw
        - POSTGRES_DB=psql_db
      ports:
        - "5432:5432"